# 운영 환경(production)을 위한 Spring Boot 설정 파일
spring:
  # 데이터베이스 연결 설정
  datasource:
    # .env 파일에 정의된 환경 변수를 사용하여 데이터베이스 연결 정보를 동적으로 설정합니다.
    # 이를 통해 민감한 정보를 코드와 분리하여 안전하게 관리할 수 있습니다.
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # JPA 및 Hibernate 설정
  jpa:
    hibernate:
      # 운영 환경에서는 애플리케이션이 스키마를 직접 변경(create, update, create-drop)하지 않도록 'none'으로 설정합니다.
      # 스키마 변경은 Flyway나 Liquibase 같은 데이터베이스 마이그레이션 도구를 통해 관리하는 것이 안전합니다.
      ddl-auto: none
    properties:
      hibernate:
        # SQL 쿼리를 보기 좋게 포맷팅하여 로그에 출력합니다.
        format_sql: true
        # 주석을 포함하여 SQL을 더 읽기 쉽게 만듭니다.
        use_sql_comments: true

# 로깅 설정
logging:
  level:
    # Hibernate가 실행하는 SQL 쿼리를 INFO 레벨 로그로 출력하도록 설정합니다.
    org.hibernate.SQL: info
    # SQL에 바인딩되는 파라미터 값을 DEBUG 레벨 로그로 출력하도록 설정합니다.
    org.hibernate.type.descriptor.sql.BasicBinder: trace 