spring:
  application:
    name: library-management-system
  
  profiles:
    active: default
  
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  
  datasource:
    url: jdbc:postgresql://localhost:5432/library_db?useUnicode=true&characterEncoding=UTF-8&stringtype=unspecified
    username: library_user
    password: library_password
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: "SET client_encoding TO 'UTF8'"
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        connection:
          characterEncoding: utf-8
          useUnicode: true
        globally_quoted_identifiers: true
  

  
  security:
    user:
      name: admin
      password: admin123

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    com.library: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# JWT 설정
jwt:
  secret: your-secret-key-here-change-in-production
  expiration: 86400000 # 24시간 (밀리초)

# 카카오 지도 API 설정
kakao:
  map:
    api-key: ${KAKAO_MAP_API_KEY:your-kakao-map-api-key} 